<template>
  <FormInput
    v-model="streamName"
    label="Stream Name"
    :placeholder="autoGeneratedName || 'Enter custom name or leave blank for auto-generation'"
    :helper-text="
      !streamName && autoGeneratedName
        ? `Auto-generated name: ${autoGeneratedName}`
        : 'Leave blank for auto-generated name or enter a custom name.'
    "
  />
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useStreamsStore } from '@/stores/streamConfig'
import FormInput from '@/components/base/FormInput.vue'
import { getFileSpec } from '@/composables/useTargetSpec'

interface Props {
  sourceConnectionId?: string | null
  targetConnectionId?: string | null
  sourceDatabase?: string | null
  targetDatabase?: string | null
}

const props = withDefaults(defineProps<Props>(), {
  sourceConnectionId: null,
  targetConnectionId: null,
  sourceDatabase: null,
  targetDatabase: null
})

const streamsStore = useStreamsStore()

const streamName = computed({
  get: () => streamsStore.currentStreamConfig?.name || '',
  set: (value) => {
    if (streamsStore.currentStreamConfig) {
      streamsStore.currentStreamConfig.name = value
    }
  }
})

const autoGeneratedName = computed(() => {
  if (!props.targetConnectionId) {
    return ''
  }

  // Use all source connections for name generation (federated mode support)
  const sourceConnections = streamsStore.currentStreamConfig?.source?.connections || []
  if (sourceConnections.length === 0) {
    return ''
  }

  const targetFileFormat = getFileSpec(streamsStore.currentStreamConfig?.target?.spec)?.fileFormat

  return streamsStore.generateDefaultStreamConfigName(
    sourceConnections,
    props.targetConnectionId,
    targetFileFormat
  )
})
</script>
