<template>
  <div
    class="bg-linear-to-br from-slate-50 to-white dark:from-gray-900 dark:via-gray-900 dark:to-gray-850 rounded-xl p-6 border border-gray-100 dark:border-gray-700 shadow-sm dark:shadow-gray-900/30"
  >
    <FormInput
      v-model="streamName"
      label="Stream Name"
      :placeholder="autoGeneratedName || 'Enter custom name or leave blank for auto-generation'"
      :helper-text="
        !streamName && autoGeneratedName
          ? `Auto-generated name: ${autoGeneratedName}`
          : 'Leave blank for auto-generated name or enter a custom name.'
      "
    />
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useStreamsStore } from '@/stores/streamConfig'
import FormInput from '@/components/base/FormInput.vue'
import { getFileSpec } from '@/composables/useTargetSpec'

interface Props {
  sourceConnectionId?: string | null
  targetConnectionId?: string | null
  sourceDatabase?: string | null
  targetDatabase?: string | null
}

const props = withDefaults(defineProps<Props>(), {
  sourceConnectionId: null,
  targetConnectionId: null,
  sourceDatabase: null,
  targetDatabase: null
})

const streamsStore = useStreamsStore()

const streamName = computed({
  get: () => streamsStore.currentStreamConfig?.name || '',
  set: (value) => {
    if (streamsStore.currentStreamConfig) {
      streamsStore.currentStreamConfig.name = value
    }
  }
})

const autoGeneratedName = computed(() => {
  if (!props.sourceConnectionId || !props.targetConnectionId) {
    return ''
  }

  // Use the existing store method to generate the name
  // Collect tables from all connections (federated mode support)
  const connections = streamsStore.currentStreamConfig?.source?.connections || []
  const allTables = connections.flatMap((conn) => conn.tables || [])
  const targetFileFormat = getFileSpec(streamsStore.currentStreamConfig?.target?.spec)?.fileFormat

  return streamsStore.generateDefaultStreamConfigName(
    props.sourceConnectionId,
    props.targetConnectionId,
    allTables,
    props.sourceDatabase || undefined,
    props.targetDatabase || undefined,
    targetFileFormat
  )
})
</script>
