<template>
  <div class="bg-white border border-gray-200 rounded-lg p-6">
    <div>
      <label for="streamName" class="block text-sm font-medium text-gray-700">Stream Name</label>
      <div class="mt-1">
        <input
          id="streamName"
          v-model="streamName"
          type="text"
          class="block w-full rounded-md border-gray-300 shadow-sm focus:border-gray-500 focus:ring-gray-500 sm:text-sm"
          :placeholder="autoGeneratedName || 'Enter custom name or leave blank for auto-generation'"
        />
      </div>
      <p v-if="!streamName && autoGeneratedName" class="mt-2 text-sm text-gray-500">
        Auto-generated name:
        <span class="font-medium text-gray-700">{{ autoGeneratedName }}</span>
      </p>
      <p v-else class="mt-2 text-sm text-gray-500">
        Leave blank for auto-generated name or enter a custom name.
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useStreamsStore } from '@/stores/streamConfig'

interface Props {
  sourceConnectionId?: string | null
  targetConnectionId?: string | null
  sourceDatabase?: string | null
  targetDatabase?: string | null
}

const props = withDefaults(defineProps<Props>(), {
  sourceConnectionId: null,
  targetConnectionId: null,
  sourceDatabase: null,
  targetDatabase: null
})

const streamsStore = useStreamsStore()

const streamName = computed({
  get: () => streamsStore.currentStreamConfig?.name || '',
  set: (value) => {
    if (streamsStore.currentStreamConfig) {
      streamsStore.currentStreamConfig.name = value
    }
  }
})

const autoGeneratedName = computed(() => {
  if (!props.sourceConnectionId || !props.targetConnectionId) {
    return ''
  }

  // Use the existing store method to generate the name
  const tables = streamsStore.currentStreamConfig?.tables || []
  const targetFileFormat = streamsStore.currentStreamConfig?.targetFileFormat

  return streamsStore.generateDefaultStreamConfigName(
    props.sourceConnectionId,
    props.targetConnectionId,
    tables,
    props.sourceDatabase || undefined,
    props.targetDatabase || undefined,
    targetFileFormat
  )
})
</script>
