<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import SlideOverPanel from '@/components/common/SlideOverPanel.vue'
import type { SQLColumnMeta } from '@/types/metadata'
import {
  emptyToNullIfNullable,
  inferEditorKind,
  normalizeDateString,
  normalizeDateTimeString,
  parseNumberInput
} from '@/utils/agGridEditing'

const props = defineProps<{
  open: boolean
  tableLabel: string
  columns: SQLColumnMeta[]
  initialValues?: Record<string, unknown>
  existingInsertId?: string | null
}>()

const emit = defineEmits<{
  (e: 'close'): void
  (e: 'insert', values: Record<string, unknown>, existingId?: string | null): void
  (e: 'insertAndAddAnother', values: Record<string, unknown>, existingId?: string | null): void
}>()

const touched = ref<Set<string>>(new Set())
const draft = reactive<Record<string, unknown>>({})

const columnByName = computed(() => {
  const m = new Map<string, SQLColumnMeta>()
  for (const c of props.columns) m.set(c.name, c)
  return m
})

function isGeneratedColumn(col: SQLColumnMeta): boolean {
  // For inserts we should not allow users to set identity-like PKs by default.
  // Some backends don't reliably flag sequence-backed PKs as autoIncrement,
  // so treat "PK + DEFAULT" as generated as well.
  return (
    Boolean(col.autoIncrement) || (Boolean(col.isPrimaryKey) && Boolean(col.defaultValue?.Valid))
  )
}

function placeholderFor(col: SQLColumnMeta): string {
  if (isGeneratedColumn(col)) return 'Generated by DB'
  if (col.defaultValue?.Valid) return `Default: ${col.defaultValue.String ?? ''}`
  if (col.isNullable) return 'NULL (leave blank)'
  return ''
}

function resetDraft() {
  touched.value = new Set()
  for (const key of Object.keys(draft)) delete draft[key]

  const initial = props.initialValues || {}
  for (const [k, v] of Object.entries(initial)) {
    const col = columnByName.value.get(k)
    if (col && isGeneratedColumn(col)) continue
    draft[k] = v
    touched.value.add(k)
  }
}

watch(
  () => [props.open, props.existingInsertId, props.initialValues] as const,
  ([open]) => {
    if (open) resetDraft()
  }
)

const requiredColumns = computed(() => {
  // Required means: NOT NULL + no DEFAULT + not autoIncrement.
  return props.columns
    .filter((c) => !c.isNullable && !c.defaultValue?.Valid && !c.autoIncrement)
    .map((c) => c.name)
})

function isMissingRequired(colName: string): boolean {
  if (!requiredColumns.value.includes(colName)) return false
  const v = draft[colName]
  if (v === null || v === undefined) return true
  if (typeof v === 'string' && v.trim() === '') return true
  return false
}

const missingRequired = computed(() => requiredColumns.value.filter((c) => isMissingRequired(c)))

function buildValuesPayload(): Record<string, unknown> {
  // Only include touched fields so DB defaults can apply.
  const out: Record<string, unknown> = {}
  for (const k of touched.value) {
    const col = columnByName.value.get(k)
    if (col && isGeneratedColumn(col)) continue
    out[k] = draft[k]
  }
  return out
}

function onSubmit(kind: 'insert' | 'insertAndAddAnother') {
  if (missingRequired.value.length > 0) return
  const values = buildValuesPayload()
  if (kind === 'insert') {
    emit('insert', values, props.existingInsertId)
  } else {
    emit('insertAndAddAnother', values, props.existingInsertId)
  }
}

function setFieldValue(col: SQLColumnMeta, raw: unknown) {
  if (isGeneratedColumn(col)) return
  const kind = inferEditorKind(col.dataType || '')
  const prev = draft[col.name]

  let next: unknown
  switch (kind) {
    case 'integer':
    case 'number':
      next = parseNumberInput(
        raw,
        kind,
        Boolean(col.isNullable),
        prev,
        col.scale?.Valid ? (col.scale.Int64 ?? 0) : undefined
      )
      break
    case 'date':
      next = normalizeDateString(raw, Boolean(col.isNullable))
      break
    case 'datetime':
      next = normalizeDateTimeString(raw, Boolean(col.isNullable))
      break
    default:
      next = emptyToNullIfNullable(raw, Boolean(col.isNullable))
      break
  }

  touched.value.add(col.name)
  draft[col.name] = next
}

function toInputValue(v: unknown): string {
  if (v === null || v === undefined) return ''
  if (typeof v === 'string') return v
  if (typeof v === 'number' || typeof v === 'boolean') return String(v)
  try {
    return JSON.stringify(v)
  } catch {
    return String(v)
  }
}

function inputTypeFor(col: SQLColumnMeta): string {
  const kind = inferEditorKind(col.dataType || '')
  if (kind === 'integer') return 'number'
  if (kind === 'date') return 'date'
  if (kind === 'datetime') return 'datetime-local'
  // Use text for decimals to avoid browser step mismatch.
  return 'text'
}
</script>

<template>
  <SlideOverPanel
    :open="open"
    :title="`New row (${tableLabel})`"
    subtitle="Fill required fields, then stage the row. Save commits it."
    @close="emit('close')"
  >
    <div class="space-y-4">
      <div
        v-if="missingRequired.length > 0"
        class="rounded-md border border-amber-200 dark:border-amber-800 bg-amber-50 dark:bg-amber-900/20 p-3"
      >
        <div class="text-xs font-semibold text-amber-800 dark:text-amber-200">
          Required fields missing
        </div>
        <div class="mt-1 text-xs text-amber-700 dark:text-amber-300">
          {{ missingRequired.join(', ') }}
        </div>
      </div>

      <div
        v-for="col in columns"
        :key="col.name"
        class="rounded-lg border border-gray-200 dark:border-gray-700 bg-gray-50/60 dark:bg-gray-900/40 p-3"
      >
        <div class="flex items-start justify-between gap-3">
          <div class="min-w-0">
            <div class="text-xs font-semibold text-gray-800 dark:text-gray-200 truncate">
              {{ col.name }}
              <span
                v-if="requiredColumns.includes(col.name)"
                class="ml-2 text-[10px] font-semibold text-red-700 dark:text-red-300"
              >
                REQUIRED
              </span>
              <span
                v-else-if="isGeneratedColumn(col)"
                class="ml-2 text-[10px] font-semibold text-gray-500 dark:text-gray-400"
              >
                GENERATED
              </span>
              <span
                v-else-if="col.defaultValue?.Valid || col.autoIncrement"
                class="ml-2 text-[10px] font-semibold text-gray-500 dark:text-gray-400"
              >
                DEFAULT
              </span>
            </div>
            <div class="mt-1 text-[10px] text-gray-600 dark:text-gray-400">
              {{ col.dataType }}
              <span v-if="!col.isNullable"> · NOT NULL</span>
              <span v-else> · NULLABLE</span>
            </div>
          </div>
        </div>

        <div class="mt-2">
          <input
            :type="inputTypeFor(col)"
            class="w-full rounded-md border px-2.5 py-2 text-sm bg-white dark:bg-gray-850 text-gray-900 dark:text-gray-100 placeholder-gray-400 dark:placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-teal-500/40"
            :disabled="isGeneratedColumn(col)"
            :class="
              isMissingRequired(col.name)
                ? 'border-red-400 dark:border-red-600'
                : 'border-gray-200 dark:border-gray-700'
            "
            :placeholder="placeholderFor(col)"
            :value="toInputValue(draft[col.name])"
            @input="(e) => setFieldValue(col, (e.target as HTMLInputElement).value)"
          />
        </div>
      </div>
    </div>

    <template #footer>
      <button
        type="button"
        class="text-xs rounded-md px-2.5 py-1 border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-gray-700 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-800"
        @click="emit('close')"
      >
        Cancel
      </button>
      <button
        type="button"
        class="text-xs rounded-md px-2.5 py-1 border border-teal-600 bg-teal-600 text-white hover:bg-teal-700 hover:border-teal-700 disabled:opacity-50 disabled:cursor-not-allowed dark:border-teal-500 dark:bg-teal-600 dark:hover:bg-teal-700"
        :disabled="missingRequired.length > 0"
        @click="onSubmit('insert')"
      >
        Insert
      </button>
      <button
        type="button"
        class="text-xs rounded-md px-2.5 py-1 border border-teal-600/50 bg-teal-50 text-teal-800 hover:bg-teal-100 disabled:opacity-50 disabled:cursor-not-allowed dark:border-teal-400/40 dark:bg-teal-900/20 dark:text-teal-200 dark:hover:bg-teal-900/30"
        :disabled="missingRequired.length > 0"
        @click="onSubmit('insertAndAddAnother')"
      >
        Insert &amp; add another
      </button>
    </template>
  </SlideOverPanel>
</template>
