#!/usr/bin/env bash
# Rebuilds AGENTS.md from .ai/instructions.md + Codex/Copilot-specific rules.
# Run this after editing .ai/instructions.md to keep AGENTS.md in sync.
#
# Usage: ./scripts/sync-agents-md.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INSTRUCTIONS="$REPO_ROOT/.ai/instructions.md"
AGENTS="$REPO_ROOT/AGENTS.md"

if [[ ! -f "$INSTRUCTIONS" ]]; then
  echo "Error: $INSTRUCTIONS not found" >&2
  exit 1
fi

cat > "$AGENTS" <<'HEADER'
# AGENTS.md

> **Auto-generated** from `.ai/instructions.md` by `scripts/sync-agents-md.sh`.
> Do not edit this file directly — edit `.ai/instructions.md` instead, then run the script.

## Codex/Copilot-Specific Rules

- Do not start or stop services automatically.
- Never run `yarn dev` — the maintainer starts the dev server manually.
- Use Yarn only (never npm/pnpm). Node >= 22 required.
- Do not commit secrets or `.env` files.

---

HEADER

cat "$INSTRUCTIONS" >> "$AGENTS"

echo "AGENTS.md synced from .ai/instructions.md"
